on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@main

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: x64

      - name: Install dependencies
        run: |
          pip install --progress-bar off pyppeteer requests

      - name: Cache headless chromium
        id: cache-chromium
        uses: actions/cache@v3
        with:
          path: ./local-chromium
          key: chromium

      - name: Install headless chromium
        if: steps.cache-chromium.outputs.cache-hit != 'true'
        env:
          PYPPETEER_HOME: ./local-chromium
        run: pyppeteer-install

      - name: Cache audio
        id: cache-audio
        uses: actions/cache@v3
        with:
          path: ./www/audio
          key: ttsaudio

      - name: Generate TTS voice files
        run: python generate_tts.py
        env:
          PYPPETEER_HOME: ./local-chromium

      - name: Pack files
        run: |
          zip -r built.zip www

      - name: Create a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: true
          title: "Auto-generated site files"
          files: |
            built.zip
